# File: .github/workflows/email-notification.yml
name: Branch Update Email Notification

# Define when this action will run
on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get the branch name
      - name: Get branch name
        id: branch-name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      # Send email using Gmail SMTP
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          # Server settings
          server_address: smtp.gmail.com
          server_port: 465
          
          # Authentication
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          
          # Email content
          subject: Cambios subidos a rama ${{ steps.branch-name.outputs.branch }}
          body: |
            Se han detectado nuevos cambios en la rama ${{ steps.branch-name.outputs.branch }}
            
            Detalles del commit:
            - Mensaje: ${{ github.event.head_commit.message }}
            - Autor: ${{ github.event.head_commit.author.name }}
            - Repositorio: ${{ github.repository }}
            
            Ver cambios: ${{ github.event.head_commit.url }}
          
          # Recipients
          to: chava.crb@gmail.com
          from: GitHub Actions <noreply@github.com>